version: '2'
services:

  php-fpm: 
    container_name: php-fpm
    build: ./php
    volumes:
      - /usr/local/www:/usr/local/www
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - /usr/local/nginx/conf:/etc/nginx/conf.d
      - /usr/local/nginx/logs:/usr/local/nginx/logs
      - /usr/local/www:/usr/local/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
        - /usr/local/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge